// webui.go implements the optional Web UI server, HTTP routes, and JSON API handlers for node operations.
// Runtime flow: Web UI is started from startup/menu actions, then handlers execute on incoming HTTP requests.

// Makes it possible to envoke actions though the Web Ui and is also used by the testing scripts for invocation.
// Triggered and called by docs are autogenerated thorugh go
package main

import (
	"crypto/elliptic"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"
)

// ===================== WEB UI =====================

// bounded in-memory log ring
type webUILogBuffer struct {
	mu      sync.Mutex
	max     int
	entries []string
	tail    string
}

// new web ui log buffer behavior for the peer runtime.
// Called by: (*TSSPeer).enableWebUILogging.
// Triggered: startup or menu action when Web UI lifecycle changes.
func newWebUILogBuffer(max int) *webUILogBuffer {
	if max <= 0 {
		max = 200
	}
	return &webUILogBuffer{max: max, entries: make([]string, 0, max)}
}

// write behavior for the runtime.
// Called by: multiple internal callers (see CALL_MAP.md).
// Triggered: Web UI runtime flow during HTTP processing.
// See CALL_MAP.md for the full direct-caller and trigger context.
func (b *webUILogBuffer) Write(p []byte) (int, error) {
	if b == nil {
		return len(p), nil
	}
	b.mu.Lock()
	defer b.mu.Unlock()

	chunk := b.tail + string(p)
	lines := strings.Split(chunk, "\n")
	if !strings.HasSuffix(chunk, "\n") {
		b.tail = lines[len(lines)-1]
		lines = lines[:len(lines)-1]
	} else {
		b.tail = ""
	}

	for _, line := range lines {
		line = strings.TrimRight(line, "\r")
		if line == "" {
			continue
		}
		b.entries = append(b.entries, line)
		if len(b.entries) > b.max {
			b.entries = b.entries[len(b.entries)-b.max:]
		}
	}
	return len(p), nil
}

// entries behavior for the peer runtime.
// Called by: (*TSSPeer).apiGetLogs.
// Triggered: Web UI runtime flow during HTTP processing.
func (b *webUILogBuffer) Entries(limit int) []string {
	if b == nil {
		return []string{}
	}
	b.mu.Lock()
	defer b.mu.Unlock()
	if limit <= 0 || limit > len(b.entries) {
		limit = len(b.entries)
	}
	out := make([]string, limit)
	copy(out, b.entries[len(b.entries)-limit:])
	return out
}

// enables web ui logging behavior for the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: startup or menu action when Web UI lifecycle changes.
func (p *TSSPeer) enableWebUILogging() {
	if !p.webuiEnabled {
		return
	}
	if p.webuiLog == nil {
		p.webuiLog = newWebUILogBuffer(200)
	}
	if p.logDefaultWriter == nil {
		p.logDefaultWriter = log.Writer()
	}
	log.SetOutput(io.MultiWriter(p.logDefaultWriter, p.webuiLog))
}

// disables web ui logging behavior for the runtime (to preserve ressources and to skew benchmarks less).
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: startup or menu action when Web UI lifecycle changes.
func (p *TSSPeer) disableWebUILogging() {
	if p.logDefaultWriter != nil {
		log.SetOutput(p.logDefaultWriter)
	}
}

// converts values to toggle the web ui (start/stop).
// Called by: (*TSSPeer).StartInteractiveMenu, main.
// Triggered: startup or menu action when Web UI lifecycle changes.
func (p *TSSPeer) toggleWebUI() {
	if p.webServer != nil {
		fmt.Println("Stopping Web UI...")
		p.webServer.Close()
		p.webServer = nil
		p.disableWebUILogging()
		fmt.Println("OK Web UI stopped")
		return
	}
	if !p.webuiEnabled {
		fmt.Println("Web UI is disabled. Set TSS_WEBUI_ENABLED=true to enable it.")
		return
	}

	port := p.webuiPort // Configured from TSS_WEBUI_PORT env or config defaults
	bind := p.webuiBind
	if strings.TrimSpace(bind) == "" {
		bind = "127.0.0.1"
	}
	mux := http.NewServeMux()

	// API endpoints
	mux.HandleFunc("/api/ca", p.apiGetCA)
	mux.HandleFunc("/api/certificates", p.apiGetCertificates)
	mux.HandleFunc("/api/certificate/status", p.apiGetCertificateStatus)
	mux.HandleFunc("/api/merkle", p.apiGetMerkle)
	mux.HandleFunc("/api/merkle/proof", p.apiGetMerkleProof)
	mux.HandleFunc("/api/dkg/fresh", p.apiForceFreshDKG)
	mux.HandleFunc("/api/csr/submit", p.apiSubmitCSR)
	mux.HandleFunc("/api/revoke", p.apiProposeRevocation)
	mux.HandleFunc("/api/membership/request", p.apiSubmitJoinRequest)
	mux.HandleFunc("/api/membership/remove", p.apiProposeMemberRemoval)
	mux.HandleFunc("/api/reshare/force", p.apiForceReshare)
	mux.HandleFunc("/api/reshare/session", p.apiGetReshareSession)
	mux.HandleFunc("/api/blocks", p.apiGetRecentBlocks)
	mux.HandleFunc("/api/keyshare", p.apiGetKeyShareInfo)
	mux.HandleFunc("/api/metrics/p2p", p.apiGetP2PStats)
	mux.HandleFunc("/api/logs", p.apiGetLogs)
	mux.HandleFunc("/assets/irs-logo.svg", p.serveIRSLogo)
	mux.HandleFunc("/", p.serveWebUI)
	if len(irsLogoSVG) == 0 {
		log.Printf("[%s] Warning: embedded IRS logo is empty; /assets/irs-logo.svg will return 503", p.NodeID)
	}

	p.webServer = &http.Server{
		Addr:    fmt.Sprintf("%s:%d", bind, port),
		Handler: mux,
	}

	go func() {
		p.enableWebUILogging()
		fmt.Printf("OK Web UI started at http://%s:%d\n", bind, port)
		if err := p.webServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Printf("[%s] Web UI error: %v", p.NodeID, err)
			p.webServer = nil
			p.disableWebUILogging()
		}
	}()
}

// json error behavior from the runtime.
// Called by: multiple internal callers (see CALL_MAP.md).
// Triggered: API request handling in the Web UI server.
// See CALL_MAP.md for the full direct-caller and trigger context.
func jsonError(w http.ResponseWriter, msg string, code int) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	resp := map[string]string{"error": msg}
	json.NewEncoder(w).Encode(resp)
}

// api gets ca from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/ca.
func (p *TSSPeer) apiGetCA(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	result, err := p.Query("GetDistributedCA", DefaultCAID)
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	w.Write(result)
}

// api gets certificates from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/certificates.
func (p *TSSPeer) apiGetCertificates(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	result, err := p.Query("GetAllCertificates")
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	if len(result) == 0 || string(result) == "null" {
		w.Write([]byte("[]"))
		return
	}
	w.Write(result)
}

// api gets certificate status from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/certificate/status.
func (p *TSSPeer) apiGetCertificateStatus(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonError(w, "GET required", http.StatusMethodNotAllowed)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	id := strings.TrimSpace(r.URL.Query().Get("id"))
	if id == "" {
		jsonError(w, "id required", http.StatusBadRequest)
		return
	}

	result, err := p.Query("GetCertificate", id)
	if err != nil {
		msg := strings.ToLower(err.Error())
		if strings.Contains(msg, "not found") || strings.Contains(msg, "does not exist") {
			jsonError(w, "certificate not found", http.StatusNotFound)
			return
		}
		jsonError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if len(result) == 0 || string(result) == "null" {
		jsonError(w, "certificate not found", http.StatusNotFound)
		return
	}

	payload := map[string]interface{}{}
	if err := json.Unmarshal(result, &payload); err != nil {
		jsonError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if len(payload) == 0 {
		jsonError(w, "certificate not found", http.StatusNotFound)
		return
	}

	getString := func(keys ...string) string {
		for _, key := range keys {
			v, ok := payload[key]
			if !ok || v == nil {
				continue
			}
			switch t := v.(type) {
			case string:
				s := strings.TrimSpace(t)
				if s != "" {
					return s
				}
			case fmt.Stringer:
				s := strings.TrimSpace(t.String())
				if s != "" {
					return s
				}
			default:
				s := strings.TrimSpace(fmt.Sprintf("%v", t))
				if s != "" && s != "<nil>" {
					return s
				}
			}
		}
		return ""
	}

	getBool := func(keys ...string) bool {
		for _, key := range keys {
			v, ok := payload[key]
			if !ok || v == nil {
				continue
			}
			switch t := v.(type) {
			case bool:
				return t
			case float64:
				return t != 0
			case int:
				return t != 0
			case string:
				s := strings.TrimSpace(strings.ToLower(t))
				if s == "" {
					continue
				}
				if s == "true" || s == "1" || s == "yes" {
					return true
				}
				if s == "false" || s == "0" || s == "no" {
					return false
				}
			}
		}
		return false
	}

	certID := getString("certId", "id")
	memberID := getString("memberId")
	proposalID := getString("proposalId")
	certificateHash := getString("certificateHash", "certHash", "hash")
	status := getString("status")
	isRevoked := getBool("isRevoked", "revoked")
	if status == "" {
		if isRevoked {
			status = "revoked"
		} else {
			status = "active"
		}
	}
	issuedAt := getString("issuedAt")
	expiresAt := getString("expiresAt")

	epoch := ""
	if raw, ok := payload["epoch"]; ok && raw != nil {
		switch t := raw.(type) {
		case float64:
			epoch = strconv.FormatInt(int64(t), 10)
		case int:
			epoch = strconv.Itoa(t)
		case string:
			epoch = strings.TrimSpace(t)
		default:
			epoch = strings.TrimSpace(fmt.Sprintf("%v", t))
		}
	}

	if certID == "" && proposalID == "" && memberID == "" {
		jsonError(w, "certificate not found", http.StatusNotFound)
		return
	}

	resp := map[string]interface{}{
		"certId":          certID,
		"memberId":        memberID,
		"certificateHash": certificateHash,
		"status":          status,
		"isRevoked":       isRevoked,
		"issuedAt":        issuedAt,
		"expiresAt":       expiresAt,
		"proposalId":      proposalID,
		"epoch":           epoch,
	}
	_ = json.NewEncoder(w).Encode(resp)
}

// api gets merkle from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/merkle.
func (p *TSSPeer) apiGetMerkle(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	enabled, err := p.GetMerkleEnabled()
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	if !enabled {
		resp := map[string]interface{}{
			"enabled":   false,
			"configSet": p.merkleConfigSet,
		}
		if p.merkleConfigSet {
			resp["configEnabled"] = p.merkleConfigEnabled
		}
		_ = json.NewEncoder(w).Encode(resp)
		return
	}

	result, err := p.Query("GetCertificateMerkleRoot")
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	if len(result) == 0 || string(result) == "null" {
		result = []byte(`{}`)
	}

	var state map[string]interface{}
	if err := json.Unmarshal(result, &state); err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	state["enabled"] = true
	state["configSet"] = p.merkleConfigSet
	if p.merkleConfigSet {
		state["configEnabled"] = p.merkleConfigEnabled
	}
	enc := json.NewEncoder(w)
	_ = enc.Encode(state)
}

// api gets merkle proof from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/merkle/proof.
func (p *TSSPeer) apiGetMerkleProof(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	hash := strings.TrimSpace(r.URL.Query().Get("hash"))
	if hash == "" {
		jsonError(w, "hash required", 400)
		return
	}
	result, err := p.Query("GetCertificateMerkleProof", hash)
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	if len(result) == 0 || string(result) == "null" {
		w.Write([]byte(`{}`))
		return
	}
	w.Write(result)
}

// api forces fresh dkg from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/dkg/fresh.
func (p *TSSPeer) apiForceFreshDKG(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		jsonError(w, "POST required", 405)
		return
	}
	w.Header().Set("Content-Type", "application/json")

	var req struct {
		Reason string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, err.Error(), 400)
		return
	}
	if strings.TrimSpace(req.Reason) == "" {
		req.Reason = "fresh_dkg"
	}

	if _, err := p.Execute("ForceFreshDKG", DefaultCAID, req.Reason); err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	resp := map[string]string{"status": "ok", "message": "fresh dkg initiated"}
	json.NewEncoder(w).Encode(resp)
}

// api submits csr from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/csr/submit.
func (p *TSSPeer) apiSubmitCSR(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		jsonError(w, "POST required", 405)
		return
	}
	w.Header().Set("Content-Type", "application/json")

	var req struct {
		CN string `json:"cn"`
		O  string `json:"o"`
		L  string `json:"l"`
		ST string `json:"st"`
		C  string `json:"c"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, err.Error(), 400)
		return
	}
	if req.CN == "" || req.O == "" || req.L == "" || req.ST == "" || req.C == "" {
		subj := parseCanonicalSubject(p.MemberID)
		if req.CN == "" {
			req.CN = subj["CN"]
		}
		if req.O == "" {
			req.O = subj["O"]
		}
		if req.L == "" {
			req.L = subj["L"]
		}
		if req.ST == "" {
			req.ST = subj["ST"]
		}
		if req.C == "" {
			req.C = subj["C"]
		}
	}
	if req.CN == "" {
		req.CN = fmt.Sprintf("%s-app", p.Organization)
	}
	if req.O == "" {
		req.O = p.Organization
	}

	proposalID := fmt.Sprintf("csr-%s-%d", p.Organization, time.Now().Unix())
	p.emitMetric("csr_api_received", map[string]interface{}{
		"proposal_id": proposalID,
		"member_id":   p.MemberID,
	})
	proposalID, err := p.SubmitCSRWithID(req.CN, req.O, req.L, req.ST, req.C, proposalID)
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	resp := map[string]string{
		"status":     "ok",
		"message":    "CSR submitted successfully",
		"proposalId": proposalID,
		"memberId":   p.MemberID,
	}
	json.NewEncoder(w).Encode(resp)
}

// api proposes revocation from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/revoke.
func (p *TSSPeer) apiProposeRevocation(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		jsonError(w, "POST required", 405)
		return
	}
	w.Header().Set("Content-Type", "application/json")

	var req struct {
		MemberID string `json:"memberId"`
		Reason   string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, err.Error(), 400)
		return
	}
	if req.MemberID == "" {
		jsonError(w, "memberId required", 400)
		return
	}
	if req.Reason == "" {
		req.Reason = "revoked via web UI"
	}

	proposalID := fmt.Sprintf("revoke-%s-%d", p.Organization, time.Now().Unix())
	_, err := p.Execute("ProposeRevocation", proposalID, req.MemberID, req.Reason)
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	p.emitMetric("revocation_proposed", map[string]interface{}{
		"proposal_id": proposalID,
		"member_id":   req.MemberID,
	})
	resp := map[string]string{"status": "ok", "proposalId": proposalID}
	json.NewEncoder(w).Encode(resp)
}

// api submits join request from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/membership/request.
func (p *TSSPeer) apiSubmitJoinRequest(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		jsonError(w, "POST required", 405)
		return
	}
	w.Header().Set("Content-Type", "application/json")

	var req struct {
		Reason string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, err.Error(), 400)
		return
	}

	proposalID := fmt.Sprintf("join-%s-%d", p.Organization, time.Now().Unix())
	if _, err := p.Execute("RequestJoinCA", DefaultCAID, proposalID, req.Reason); err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	p.emitMetric("join_request_submitted", map[string]interface{}{
		"proposal_id": proposalID,
		"member_id":   p.MemberID,
	})

	resp := map[string]string{"status": "ok", "proposalId": proposalID}
	json.NewEncoder(w).Encode(resp)
}

// api proposes member removal from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/membership/remove.
func (p *TSSPeer) apiProposeMemberRemoval(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		jsonError(w, "POST required", 405)
		return
	}
	w.Header().Set("Content-Type", "application/json")

	var req struct {
		MemberID string `json:"memberId"`
		Reason   string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, err.Error(), 400)
		return
	}
	if strings.TrimSpace(req.MemberID) == "" {
		jsonError(w, "memberId required", 400)
		return
	}

	shortLabel := strings.TrimSuffix(p.extractShortNodeID(req.MemberID), "-peer")
	proposalID := fmt.Sprintf("remove-%s-%d", shortLabel, time.Now().Unix())
	if _, err := p.Execute("ProposeRemoveMember", DefaultCAID, proposalID, req.MemberID, req.Reason); err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	p.emitMetric("member_removal_proposed", map[string]interface{}{
		"proposal_id": proposalID,
		"member_id":   req.MemberID,
	})

	resp := map[string]string{"status": "ok", "proposalId": proposalID}
	json.NewEncoder(w).Encode(resp)
}

// api forces reshare in the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/reshare/force.
func (p *TSSPeer) apiForceReshare(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		jsonError(w, "POST required", 405)
		return
	}
	w.Header().Set("Content-Type", "application/json")

	var req struct {
		Reason string `json:"reason"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonError(w, err.Error(), 400)
		return
	}
	if strings.TrimSpace(req.Reason) == "" {
		req.Reason = "manual_reshare"
	}

	log.Printf("[%s] API force reshare requested (reason=%s)", p.NodeID, req.Reason)
	if _, err := p.Execute("ForceReshare", DefaultCAID, req.Reason); err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	resp := map[string]string{"status": "ok", "message": "reshare requested"}
	json.NewEncoder(w).Encode(resp)
}

// api gets reshare session from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/reshare/session.
func (p *TSSPeer) apiGetReshareSession(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonError(w, "GET required", http.StatusMethodNotAllowed)
		return
	}
	w.Header().Set("Content-Type", "application/json")

	epoch := -1
	if raw := strings.TrimSpace(r.URL.Query().Get("epoch")); raw != "" {
		v, err := strconv.Atoi(raw)
		if err != nil {
			jsonError(w, "invalid epoch", http.StatusBadRequest)
			return
		}
		epoch = v
	} else {
		caBytes, err := p.Query("GetDistributedCA", DefaultCAID)
		if err != nil {
			jsonError(w, err.Error(), http.StatusInternalServerError)
			return
		}
		var ca map[string]interface{}
		if err := json.Unmarshal(caBytes, &ca); err != nil {
			jsonError(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if v, ok := ca["epoch"].(float64); ok {
			epoch = int(v)
		}
	}
	if epoch < 0 {
		jsonError(w, "unable to resolve epoch", http.StatusInternalServerError)
		return
	}

	reshareBytes, err := p.Query("GetReshareSession", fmt.Sprintf("%d", epoch))
	if err != nil {
		if containsIgnoreCase(err.Error(), "reshare session not found") {
			jsonError(w, err.Error(), http.StatusNotFound)
			return
		}
		jsonError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if len(reshareBytes) == 0 || string(reshareBytes) == "null" {
		jsonError(w, "reshare session not found", http.StatusNotFound)
		return
	}
	w.Write(reshareBytes)
}

//	api gets recent blocks from the runtime.
//
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/blocks.
func (p *TSSPeer) apiGetRecentBlocks(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	limit := 5
	if raw := r.URL.Query().Get("limit"); raw != "" {
		if v, err := strconv.Atoi(raw); err == nil {
			limit = v
		}
	}
	blocks, err := p.getRecentBlocks(limit)
	if err != nil {
		jsonError(w, err.Error(), 500)
		return
	}
	json.NewEncoder(w).Encode(blocks)
}

// api get key share info behavior from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/keyshare.
func (p *TSSPeer) apiGetKeyShareInfo(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	p.mutex.RLock()
	defer p.mutex.RUnlock()
	runtimeMode := "observer-lite"
	if p.isMember {
		runtimeMode = "member-active"
	}

	info := map[string]interface{}{
		"nodeId":               p.NodeID,
		"memberId":             p.MemberID,
		"organization":         p.Organization,
		"threshold":            p.Threshold,
		"keySessionInProgress": p.keygenInProgress,
		"keySessionEpoch":      p.keygenEpoch,
		"signingInProgress":    p.signingInProgress,
		"partyIndex":           p.myPartyIndex,
		"hasKeyShare":          p.TSSKeyShare != nil,
		"autoRestoreSnapshot":  p.autoRestoreSnapshot,
		"snapshotConfigured":   len(p.snapshotKey) == 32,
		"snapshotRetention":    p.snapshotRetention,
		"runtimeMode":          runtimeMode,
		"certSyncMode":         fmt.Sprintf("OK"),
		"executeRetry": map[string]interface{}{
			"maxAttempts":      p.executeMaxAttempts,
			"backoffBaseMs":    int(p.executeBackoffBase / time.Millisecond),
			"backoffMaxMs":     int(p.executeBackoffMax / time.Millisecond),
			"backoffJitterPct": p.executeBackoffJitterPct,
		},
	}
	if p.TSSKeyShare != nil && p.TSSKeyShare.ECDSAPub != nil {
		pubBytes := elliptic.Marshal(
			p.TSSKeyShare.ECDSAPub.Curve(),
			p.TSSKeyShare.ECDSAPub.X(),
			p.TSSKeyShare.ECDSAPub.Y(),
		)
		info["caPublicKey"] = hex.EncodeToString(pubBytes)
	}
	json.NewEncoder(w).Encode(info)
}

// api get logs from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/logs.
func (p *TSSPeer) apiGetLogs(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	if p.webuiLog == nil {
		w.Write([]byte("[]"))
		return
	}
	limit := 120
	if raw := r.URL.Query().Get("limit"); raw != "" {
		if v, err := strconv.Atoi(raw); err == nil && v > 0 {
			limit = v
		}
	}
	entries := p.webuiLog.Entries(limit)
	json.NewEncoder(w).Encode(entries)
}

// implements api get p2p stats behavior from the runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /api/metrics/p2p.
func (p *TSSPeer) apiGetP2PStats(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonError(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	reset := false
	if val := r.URL.Query().Get("reset"); val != "" {
		switch strings.ToLower(val) {
		case "1", "true", "yes", "y":
			reset = true
		}
	}
	stats := p.p2pStats.snapshot(reset)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(stats)
}

// serves web ui behavior for the peer runtime.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /.
func (p *TSSPeer) serveWebUI(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, webUIHTML)
}

// serves irs logo for the web UI.
// Called by: (*TSSPeer).toggleWebUI.
// Triggered: API request through Web UI route(s): /assets/irs-logo.svg.
func (p *TSSPeer) serveIRSLogo(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if len(irsLogoSVG) == 0 {
		http.Error(w, "logo not available", http.StatusServiceUnavailable)
		return
	}
	w.Header().Set("Content-Type", "image/svg+xml; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store, no-cache, must-revalidate")
	w.Header().Set("Pragma", "no-cache")
	w.Header().Set("Expires", "0")
	_, _ = w.Write(irsLogoSVG)
}

const webUIHTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Decentralized PKI - Web UI</title>
<style>
:root{
--kit-green:rgb(0,150,130);
--kit-blue:rgb(70,100,170);
--kit-brown:rgb(167,130,46);
--kit-purple:rgb(163,16,124);
--kit-cyan:rgb(35,161,224);
--kit-may-green:rgb(140,182,60);
--kit-yellow:rgb(252,229,0);
--kit-orange:rgb(223,155,27);
--kit-red:rgb(162,34,35);
--kit-black:rgb(0,0,0);
--kit-gray-20:rgb(51,51,51);
--kit-gray-40:rgb(102,102,102);
--kit-gray-60:rgb(153,153,153);
--kit-gray-80:rgb(204,204,204);
--kit-white:rgb(255,255,255)
}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:Arial,Helvetica,sans-serif;background:
linear-gradient(180deg,rgba(0,150,130,0.16) 0%,rgba(35,161,224,0.10) 48%,rgba(255,255,255,1) 100%);
color:var(--kit-gray-20);min-height:100vh}
.header{background:linear-gradient(110deg,rgba(0,150,130,0.09) 0%,rgba(70,100,170,0.09) 100%),var(--kit-white);padding:1.1rem 1.6rem;border-bottom:2px solid var(--kit-green);display:flex;align-items:center;gap:0.75rem;box-shadow:0 8px 24px rgba(0,0,0,0.12)}
.header-main{display:flex;align-items:center;gap:0.75rem;flex-wrap:wrap}
.header h1{font-size:1.35rem;font-weight:700;color:var(--kit-green);letter-spacing:0.02em}
.header .badge{background:rgba(0,150,130,0.12);color:var(--kit-green);padding:0.2rem 0.75rem;border-radius:999px;font-size:0.78rem;border:1px solid rgba(0,150,130,0.35)}
#caStatus{background:rgba(0,150,130,0.16);color:rgb(0,120,104);border-color:rgba(0,150,130,0.45)}
.logo-wrap{margin-left:auto;display:flex;align-items:center;justify-content:flex-end}
.logo-wrap img{height:42px;width:auto;max-width:160px}
.container{display:grid;grid-template-columns:1fr 1fr;gap:1.25rem;padding:1.25rem;max-width:1400px;margin:0 auto}
.card{background:var(--kit-white);border:1px solid var(--kit-gray-80);border-radius:0.9rem;padding:1.1rem 1.2rem;overflow:hidden;box-shadow:0 10px 20px rgba(51,51,51,0.12)}
.card h2{font-size:0.95rem;color:var(--kit-green);margin-bottom:0.85rem;display:flex;align-items:center;gap:0.5rem}
.card h2::before{content:'';display:inline-block;width:4px;height:1rem;background:var(--kit-green);border-radius:2px}
.full{grid-column:1/-1}
table{width:100%;border-collapse:collapse;font-size:0.85rem}
th{text-align:left;padding:0.55rem;color:var(--kit-gray-40);border-bottom:1px solid var(--kit-gray-80);font-weight:700;background:rgba(204,204,204,0.2)}
td{padding:0.55rem;border-bottom:1px solid rgba(204,204,204,0.65);word-break:break-all;max-width:300px}
.status{padding:0.15rem 0.5rem;border-radius:0.25rem;font-size:0.75rem;font-weight:600;display:inline-block}
.status.active{background:rgba(0,150,130,0.16);color:rgb(0,120,104);border:1px solid rgba(0,150,130,0.45)}
.status.revoked{background:rgba(162,34,35,0.14);color:var(--kit-red);border:1px solid rgba(162,34,35,0.35)}
.btn{padding:0.5rem 1rem;border:1px solid transparent;border-radius:0.6rem;cursor:pointer;font-size:0.85rem;font-weight:700;transition:all 0.2s}
.btn-primary{background:var(--kit-green);border-color:var(--kit-green);color:var(--kit-white)}
.btn-primary:hover{background:rgb(0,130,112);border-color:rgb(0,130,112)}
.btn-danger{background:var(--kit-red);border-color:var(--kit-red);color:var(--kit-white)}
.btn-danger:hover{background:rgb(132,28,28);border-color:rgb(132,28,28)}
.btn-sm{padding:0.3rem 0.6rem;font-size:0.75rem}
.actions{display:flex;gap:0.5rem;flex-wrap:wrap;margin-top:1rem}
input,select{background:var(--kit-white);color:var(--kit-gray-20);border:1px solid var(--kit-gray-60);border-radius:0.45rem;padding:0.45rem 0.6rem;font-size:0.85rem;width:100%}
input:focus,select:focus{outline:none;border-color:var(--kit-green);box-shadow:0 0 0 2px rgba(0,150,130,0.2)}
.form-row{display:grid;grid-template-columns:1fr 1fr;gap:0.5rem;margin-bottom:0.5rem}
.member-grid{display:grid;gap:0.75rem}
.member-block{background:rgba(0,150,130,0.05);border:1px solid rgba(0,150,130,0.22);border-radius:0.7rem;padding:0.8rem}
.member-heading{font-size:0.72rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--kit-green);margin-bottom:0.5rem;font-weight:700}
label{font-size:0.75rem;color:var(--kit-gray-40);margin-bottom:0.2rem;display:block}
.member-list{list-style:none;margin:0;padding:0;display:grid;gap:0.35rem}
.member-list li{padding:0.35rem 0.45rem;background:rgba(0,150,130,0.06);border:1px solid rgba(0,150,130,0.2);border-radius:0.35rem}
.member-short{display:block;font-weight:700;color:var(--kit-green)}
.member-full{display:block;font-family:monospace;font-size:0.72rem;color:var(--kit-gray-40);word-break:break-all}
.merkle-root{font-family:monospace;font-size:0.8rem;background:var(--kit-gray-20);padding:0.75rem;border-radius:0.375rem;word-break:break-all;color:var(--kit-cyan)}
.info-grid{display:grid;grid-template-columns:auto 1fr;gap:0.25rem 0.75rem;font-size:0.85rem}
.info-grid dt{color:var(--kit-gray-40)}.info-grid dd{color:var(--kit-gray-20);word-break:break-all}
.warn{color:var(--kit-red);font-weight:700}
.keyshare-flag{display:inline-block;padding:0.2rem 0.65rem;border-radius:999px;font-size:0.75rem;font-weight:700;letter-spacing:0.02em}
.keyshare-flag.ok{background:rgba(0,150,130,0.16);color:rgb(0,120,104);border:1px solid rgba(0,150,130,0.45)}
.keyshare-flag.missing{background:rgba(162,34,35,0.14);color:var(--kit-red);border:1px solid rgba(162,34,35,0.35)}
.divider{height:1px;background:var(--kit-gray-80);margin:0.85rem 0}
.details{margin-top:0.75rem}
.details summary{list-style:none;cursor:pointer;color:var(--kit-green);font-weight:700;padding:0.35rem 0;display:flex;align-items:center;gap:0.5rem}
.details summary::-webkit-details-marker{display:none}
.details summary::before{content:'>';color:var(--kit-green);transition:transform 0.2s}
.details[open] summary::before{transform:rotate(90deg)}
.toast{position:fixed;top:1rem;right:1rem;padding:0.75rem 1.25rem;border-radius:0.5rem;color:white;font-size:0.85rem;z-index:999;animation:fade 3s forwards}
.toast.ok{background:var(--kit-green)}.toast.err{background:var(--kit-red)}
@keyframes fade{0%,70%{opacity:1}100%{opacity:0}}
.spinner{display:inline-block;width:1rem;height:1rem;border:2px solid var(--kit-gray-80);border-top-color:var(--kit-green);border-radius:50%;animation:spin 0.6s linear infinite}
@keyframes spin{to{transform:rotate(360deg)}}
.empty{color:var(--kit-gray-60);font-style:italic;padding:1rem;text-align:center}
.modal{position:fixed;inset:0;background:rgba(0,0,0,0.65);display:none;align-items:center;justify-content:center;z-index:1000}
.modal.show{display:flex}
.modal-content{background:var(--kit-white);border:1px solid var(--kit-gray-80);border-radius:0.75rem;max-width:800px;width:92%;padding:1rem}
.modal-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:0.5rem}
.modal-content pre{white-space:pre-wrap;word-break:break-all;font-size:0.8rem;background:rgba(204,204,204,0.22);padding:0.75rem;border-radius:0.5rem;max-height:60vh;overflow:auto}
.log-box{background:var(--kit-gray-20);border:1px solid var(--kit-black);border-radius:0.6rem;padding:0.75rem;font-family:monospace;font-size:0.75rem;line-height:1.2;max-height:240px;overflow:auto;white-space:pre-wrap;color:var(--kit-white)}
@media(max-width:980px){
.container{grid-template-columns:1fr;padding:1rem}
.header{padding:1rem;flex-wrap:wrap}
.header-main{width:100%}
.logo-wrap{width:100%;margin-left:0}
.logo-wrap img{height:34px;max-width:130px}
}
</style>
</head>
<body>
<div class="header">
<div class="header-main">
<h1>Decentralized PKI</h1>
<span class="badge" id="nodeLabel">loading...</span>
<span class="badge" id="caStatus">CA: loading</span>
</div>
<div class="logo-wrap"><img src="/assets/irs-logo.svg" alt="IRS logo"></div>
</div>
<div class="container">

<div class="card">
<h2>CA State</h2>
<dl class="info-grid" id="caInfo"><dt>Loading...</dt><dd></dd></dl>
</div>

<div class="card">
<h2>Key Share Info</h2>
<dl class="info-grid" id="keyInfo"><dt>Loading...</dt><dd></dd></dl>
</div>

<div class="card">
<h2>Request Certificate</h2>
<div class="form-row">
<div><label>Common Name (CN)</label><input id="csrCN" placeholder="e.g. User@IRS-X"></div>
<div><label>Organization (O)</label><input id="csrO" placeholder="e.g. IRS-X"></div>
</div>
<div class="form-row">
<div><label>Locality (L)</label><input id="csrL" placeholder="e.g. Karlsruhe"></div>
<div><label>State (ST)</label><input id="csrST" placeholder="e.g. BW"></div>
</div>
<div class="form-row">
<div><label>Country (C)</label><input id="csrC" placeholder="e.g. DE"></div>
<div style="display:flex;align-items:flex-end"><button class="btn btn-primary" onclick="submitCSR()">Submit CSR</button></div>
</div>
</div>

<div class="card">
<h2>Membership</h2>
<div class="member-grid">
<div class="member-block">
<div class="member-heading">Join</div>
<div class="form-row">
<div><label>Join Reason</label><input id="joinReason" placeholder="e.g. new node join"></div>
<div style="display:flex;align-items:flex-end"><button class="btn btn-primary" onclick="submitJoinRequest()">Request Membership</button></div>
</div>
</div>
</div>
<details class="details">
<summary>Advanced Membership & Key Ops</summary>
<div class="member-grid">
<div class="member-block">
<div class="member-heading">Member Removal</div>
<div class="form-row">
<div><label>Remove Member</label><select id="removeMemberId"></select></div>
<div><label>Reason</label><input id="removeReason" placeholder="e.g. compromised"></div>
</div>
<div class="actions">
<button class="btn btn-danger" onclick="submitRemoveMember()">Propose Removal</button>
</div>
</div>
<div class="member-block">
<div class="member-heading">Reshare / Reset</div>
<div class="form-row">
<div><label>Manual Reshare Reason</label><input id="forceReshareReason" placeholder="e.g. manual reshare"></div>
<div style="display:flex;align-items:flex-end"><button class="btn btn-primary" onclick="submitForceReshare()">Force Reshare</button></div>
</div>
<div class="divider"></div>
<div class="form-row">
<div><label>Fresh DKG Reason</label><input id="freshDkgReason" placeholder="e.g. reset key"></div>
<div style="display:flex;align-items:flex-end"><button class="btn btn-danger" onclick="submitFreshDKG()">Force Fresh DKG</button></div>
</div>
</div>
</div>
</details>
</div>

<div class="card full">
<h2>Issued Certificates</h2>
<table>
<thead><tr><th>Subject</th><th>Serial</th><th>Status</th><th>Issued</th><th>Expires</th><th>Actions</th></tr></thead>
<tbody id="certTable"><tr><td colspan="6" class="empty">Loading...</td></tr></tbody>
</table>
</div>

<div class="card">
<details class="details">
<summary>Merkle Tree</summary>
<div id="merkleInfo" class="empty">Loading...</div>
<div class="form-row" style="margin-top:0.75rem">
<div><label>Certificate Hash</label><input id="merkleProofHash" placeholder="hex certificate hash"></div>
<div style="display:flex;align-items:flex-end"><button class="btn btn-primary" onclick="getMerkleProofFromInput()">Get Proof</button></div>
</div>
</details>
</div>

<div class="card full">
<details class="details">
<summary>Recent Blocks</summary>
<table>
<thead><tr><th>Block</th><th>TxID</th><th>Type</th></tr></thead>
<tbody id="blockTable"><tr><td colspan="3" class="empty">Loading...</td></tr></tbody>
</table>
</details>
</div>

<div class="card full">
<h2>Recent Log</h2>
<pre id="logBox" class="log-box">Loading...</pre>
</div>

</div>

<div id="proofModal" class="modal" onclick="hideProof(event)">
<div class="modal-content" onclick="event.stopPropagation()">
  <div class="modal-header">
    <strong>Merkle Proof</strong>
    <button class="btn btn-sm" onclick="hideProof()">Close</button>
  </div>
  <pre id="proofContent">Loading...</pre>
</div>
</div>

<script>
const API='';
const csrDefaults={cn:'User@IRS-X',o:'IRS-X',l:'Karlsruhe',st:'BW',c:'DE'};
function toast(msg,ok){const d=document.createElement('div');d.className='toast '+(ok?'ok':'err');d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),3200)}
function showProof(data){
  const modal=document.getElementById('proofModal');
  const pre=document.getElementById('proofContent');
  if(pre){pre.textContent=JSON.stringify(data,null,2);}
  if(modal){modal.classList.add('show');}
}
function hideProof(){
  const modal=document.getElementById('proofModal');
  if(modal){modal.classList.remove('show');}
}
async function fetchMerkleProof(hash){
  if(!hash){toast('No cert hash available',false);return;}
  try{
    const r=await fetch(API+'/api/merkle/proof?hash='+encodeURIComponent(hash));
    const d=await r.json();
    if(r.ok){showProof(d);} else {toast(d.error||'Failed',false);}
  }catch(e){toast(e.message,false)}
}
function getMerkleProofFromInput(){
  const el=document.getElementById('merkleProofHash');
  const hash=(el&&el.value)?el.value.trim():'';
  if(!hash){toast('Enter certificate hash',false);return;}
  fetchMerkleProof(hash);
}
function shortMember(id){
  if(!id) return '';
  const p=id.split('::');
  if(p.length>1){return p[1].split(',')[0];}
  return id.length>40? id.substring(0,40)+'...' : id;
}
function populateMemberSelect(members){
  const sel=document.getElementById('removeMemberId');
  if(!sel) return;
  sel.innerHTML='';
  if(!members || members.length===0){
    const opt=document.createElement('option');
    opt.value='';
    opt.textContent='No members';
    sel.appendChild(opt);
    sel.disabled=true;
    return;
  }
  sel.disabled=false;
  members.forEach(m=>{
    const opt=document.createElement('option');
    opt.value=m;
    opt.textContent=shortMember(m);
    sel.appendChild(opt);
  });
}

function setCsrDefaults(){
  const map={csrCN:'cn',csrO:'o',csrL:'l',csrST:'st',csrC:'c'};
  Object.keys(map).forEach(id=>{
    const el=document.getElementById(id);
    if(el && !el.value){el.value=csrDefaults[map[id]];}
  });
}

function orgSuffixFromOrg(org){
  if(!org) return 'X';
  const match=String(org).trim().match(/(\d+)$/);
  return match ? match[1] : 'X';
}

function updateCsrDefaultsFromOrg(org){
  const n=orgSuffixFromOrg(org);
  csrDefaults.cn='User@IRS-'+n;
  csrDefaults.o='IRS-'+n;
}

let __caPublicKey='';
let __caMemberCount=0;
let __org='';

async function loadCA(){
  try{
    const r=await fetch(API+'/api/ca');const d=await r.json();
    const el=document.getElementById('caInfo');
    const esc=(v)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
    const memberRaw=d.members||[];
    const membersHTML=memberRaw.length===0
      ? '<span class="empty">No CA members</span>'
      : '<ul class="member-list">'+memberRaw.map(m=>'<li><span class="member-short">'+esc(shortMember(m))+'</span><span class="member-full">'+esc(m)+'</span></li>').join('')+'</ul>';
    const n=(d.thresholdParams?.totalNodes??0);
    const t=(d.thresholdParams?.threshold??null);
    const quorum=(d.governanceParams?.quorumPercentage??null);
    let required='-';
    if(n){
      if(t!==null && t!==undefined){
        required=t+1;
      }else if(quorum!==null && quorum!==undefined){
        required=Math.max(2, Math.ceil(n*quorum/100));
      }
    }
    const keyEpoch=(d.publicKey&&d.epoch!==undefined&&d.epoch!==null)?d.epoch:'-';
    const keyLabel=d.publicKey?(d.publicKey.substring(0,24)+'...'+d.publicKey.slice(-12)):'not set';
    el.innerHTML='<dt>Name</dt><dd>'+(d.name||'root-ca')+'</dd>'+
      '<dt>Epoch</dt><dd>'+d.epoch+'</dd>'+
      '<dt>Members</dt><dd>'+membersHTML+'</dd>'+
      '<dt>Required Signers</dt><dd>'+required+' of '+(n||'-')+(quorum!==null?' (quorum '+quorum+'%)':'')+'</dd>'+
      '<dt>Current Key Epoch</dt><dd>'+keyEpoch+'</dd>'+
      '<dt>Current Key</dt><dd style="font-family:monospace;font-size:0.75rem">'+keyLabel+'</dd>';
      document.getElementById('caStatus').textContent='CA: '+(d.isActive?'Active':'Inactive')+' (epoch '+d.epoch+')';
      populateMemberSelect(d.members||[]);
      __caPublicKey=d.publicKey||'';
    __caMemberCount=(d.members||[]).length;
  }catch(e){console.error(e)}
}

async function loadCerts(){
  try{
    const r=await fetch(API+'/api/certificates');const d=await r.json();
    const el=document.getElementById('certTable');
    if(!d||d.length===0){el.innerHTML='<tr><td colspan="6" class="empty">No certificates issued yet</td></tr>';return}
    el.innerHTML=d.map(c=>{
      const st=c.isRevoked?'revoked':'active';
      const issued=c.issuedAt?new Date(c.issuedAt).toLocaleDateString():'-';
      const expires=c.expiresAt?new Date(c.expiresAt).toLocaleDateString():'-';
      const serial=c.serialNumber&&c.serialNumber.length>16?c.serialNumber.substring(0,16)+'...':c.serialNumber;
    const mid=c.memberId||'';
    const certHash=c.certHash||c.certificateHash||'';
    const revBtn=st==='active'?'<button class="btn btn-danger btn-sm" onclick="revokeCert(\''+mid.replace(/'/g,"\\'")+'\')">Revoke</button>':'';
    const proofBtn=certHash?'<button class="btn btn-primary btn-sm" onclick="fetchMerkleProof(\''+certHash.replace(/'/g,"\\'")+'\')">Proof</button>':'';
    const actions=[revBtn,proofBtn].filter(Boolean).join(' ');
    return '<tr><td>'+c.subject+'</td><td style="font-family:monospace;font-size:0.75rem">'+serial+'</td>'+
      '<td><span class="status '+st+'">'+st+'</span></td><td>'+issued+'</td><td>'+expires+'</td><td>'+actions+'</td></tr>';
  }).join('');
  }catch(e){console.error(e)}
}

async function loadMerkle(){
  try{
    const r=await fetch(API+'/api/merkle');const d=await r.json();
    const el=document.getElementById('merkleInfo');
    const enabled = d.enabled !== false;
    let html='<div style="margin-bottom:0.5rem"><strong>Status:</strong> '+(enabled?'Enabled':'Disabled')+'</div>';
    if(!enabled){el.innerHTML=html+'<span class="empty">Merkle tree disabled</span>';return}
    if(!d.merkleRoot){el.innerHTML=html+'<span class="empty">No Merkle root yet</span>';return}
    el.innerHTML=html+'<div class="merkle-root">'+d.merkleRoot+'</div>'+
      '<div style="margin-top:0.75rem;font-size:0.85rem"><strong>Active certs:</strong> '+d.activeCertCount+
      ' &nbsp; <strong>Updated:</strong> '+new Date(d.updatedAt).toLocaleString()+
      ' &nbsp; <strong>Action:</strong> '+d.triggerAction+'</div>';
  }catch(e){console.error(e)}
}

async function loadKeyInfo(){
  try{
    const r=await fetch(API+'/api/keyshare');const d=await r.json();
    const el=document.getElementById('keyInfo');
    document.getElementById('nodeLabel').textContent=d.nodeId+' ('+d.organization+')';
    __org=d.organization||'';
  updateCsrDefaultsFromOrg(__org);
    setCsrDefaults();
    const hasKey=!!d.hasKeyShare;
    const keyPresenceClass=hasKey?'ok':'missing';
    const keyPresenceLabel=hasKey?'AVAILABLE':'MISSING';
    let keyStatus='-';
    if(hasKey){
      if(__caPublicKey && d.caPublicKey && __caPublicKey!==d.caPublicKey){
        keyStatus='Stale (reshare needed)';
      }else{
        keyStatus='OK';
      }
    }
    const snapshotLine=d.autoRestoreSnapshot
      ? ('Enabled (key '+(d.snapshotConfigured?'configured':'missing')+', keep '+(d.snapshotRetention||0)+')')
      : 'Disabled';
    el.innerHTML='<dt>Node ID</dt><dd>'+d.nodeId+'</dd>'+
      '<dt>Key Share Presence</dt><dd><span class="keyshare-flag '+keyPresenceClass+'">'+keyPresenceLabel+'</span></dd>'+
      '<dt>Key Share Status</dt><dd class="'+(keyStatus.startsWith('Stale')?'warn':'')+'">'+keyStatus+'</dd>'+
      '<dt>Cert Sync</dt><dd>'+(d.certSyncMode||'Event-driven updates with poll fallback')+'</dd>'+
      '<dt>Party Index</dt><dd>'+d.partyIndex+'</dd>'+
      '<dt>Snapshot Restore</dt><dd>'+snapshotLine+'</dd>'+
      '<dt>CA Public Key</dt><dd style="font-family:monospace;font-size:0.75rem">'+(d.caPublicKey?d.caPublicKey.substring(0,40)+'...':'-')+'</dd>';
  }catch(e){console.error(e)}
}

async function loadBlocks(){
  try{
    const r=await fetch(API+'/api/blocks?limit=5');const d=await r.json();
    const el=document.getElementById('blockTable');
  if(!d || d.length===0){el.innerHTML='<tr><td colspan="3" class="empty">No blocks</td></tr>';return}
    const rows=[];
    d.forEach(b=>{
      const label='#'+b.number+' ('+b.txCount+')';
    if(!b.txs || b.txs.length===0){
      rows.push('<tr><td>'+label+'</td><td>-</td><td>-</td></tr>');
      return;
    }
    b.txs.forEach(tx=>{
      const txid=tx.txId? (tx.txId.length>12?tx.txId.substring(0,12)+'...':tx.txId) : '-';
      rows.push('<tr><td>'+label+'</td><td style="font-family:monospace;font-size:0.75rem">'+txid+
        '</td><td>'+ (tx.type||'-') +'</td></tr>');
    });
    });
    el.innerHTML=rows.join('');
  }catch(e){console.error(e)}
}

async function loadLogs(){
  const el=document.getElementById('logBox');
  if(!el) return;
  try{
    const r=await fetch(API+'/api/logs?limit=120');const d=await r.json();
    if(!d || d.length===0){el.textContent='No log entries yet';return}
    el.textContent=d.join('\n');
    el.scrollTop=el.scrollHeight;
  }catch(e){console.error(e)}
}

async function submitCSR(){
  const cnRaw=document.getElementById('csrCN').value;
  const oRaw=document.getElementById('csrO').value;
  const body={
    cn:cnRaw||csrDefaults.cn,
    o:oRaw||csrDefaults.o,
    l:document.getElementById('csrL').value||csrDefaults.l,
    st:document.getElementById('csrST').value||csrDefaults.st,
    c:document.getElementById('csrC').value||csrDefaults.c
  };
  try{
    const r=await fetch(API+'/api/csr/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
    const d=await r.json();
    if(r.ok){toast('CSR submitted! Waiting for CA approval...',true);setCsrDefaults()}
    else toast(d.error||'Failed',false);
  }catch(e){toast(e.message,false)}
}

async function submitJoinRequest(){
  const reason=document.getElementById('joinReason').value||'';
  try{
    const r=await fetch(API+'/api/membership/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});
    const d=await r.json();
    if(r.ok){toast('Join request submitted: '+(d.proposalId||''),true);document.getElementById('joinReason').value=''}
    else toast(d.error||'Failed',false);
  }catch(e){toast(e.message,false)}
}

async function submitRemoveMember(){
  const sel=document.getElementById('removeMemberId');
  const memberId=sel?sel.value:'';
  const reason=document.getElementById('removeReason').value||'';
  if(!memberId){toast('Select a member to remove',false);return}
  try{
    const r=await fetch(API+'/api/membership/remove',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({memberId,reason})});
    const d=await r.json();
    if(r.ok){toast('Removal proposed: '+(d.proposalId||''),true);document.getElementById('removeReason').value=''}
    else toast(d.error||'Failed',false);
  }catch(e){toast(e.message,false)}
}

async function submitForceReshare(){
  if(!confirm('Force a manual reshare for the current CA membership?')){return}
  const reason=document.getElementById('forceReshareReason').value||'manual_reshare';
  try{
    const r=await fetch(API+'/api/reshare/force',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({reason})});
    const d=await r.json();
    if(r.ok){toast('Reshare requested',true);document.getElementById('forceReshareReason').value=''}
    else toast(d.error||'Failed',false);
  }catch(e){toast(e.message,false)}
}

async function submitFreshDKG(){
  if(!confirm('Force a fresh DKG? This resets the CA public key and invalidates old certs.')){return}
  const reason=document.getElementById('freshDkgReason').value||'fresh_dkg';
  try{
    const r=await fetch(API+'/api/dkg/fresh',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({reason})});
    const d=await r.json();
    if(r.ok){toast('Fresh DKG requested',true);document.getElementById('freshDkgReason').value=''}
    else toast(d.error||'Failed',false);
  }catch(e){toast(e.message,false)}
}

async function revokeCert(memberId){
  if(!confirm('Revoke certificate for this member?'))return;
  const reason=prompt('Revocation reason:','key compromise');
  if(reason===null)return;
  try{
    const r=await fetch(API+'/api/revoke',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({memberId,reason})});
    const d=await r.json();
    if(r.ok){toast('Revocation proposed: '+d.proposalId,true)}
    else toast(d.error||'Failed',false);
  }catch(e){toast(e.message,false)}
}

function refreshAll(){loadCA();loadCerts();loadBlocks();loadMerkle();loadKeyInfo();loadLogs()}
setCsrDefaults();
refreshAll();
setInterval(refreshAll,10000);
setInterval(loadLogs,3000);
</script>
</body>
</html>`
